# Generated by Django 3.1.2 on 2020-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0003_auto_20201012_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_favorite_album',
            field=models.BooleanField(default=False),
        ),
    ]
