# Generated by Django 3.1.2 on 2020-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0004_album_is_favorite_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.ManyToManyField(related_name='favAlbum', to='fpage.Album')),
            ],
        ),
    ]
