# Generated by Django 3.1.2 on 2020-10-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0005_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favourite',
        ),
    ]
