# Generated by Django 3.1.2 on 2020-11-11 16:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0013_auto_20201109_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
