# Generated by Django 3.1.2 on 2020-11-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpage', '0015_watchlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlater',
            name='video_id',
            field=models.TextField(default=''),
        ),
    ]
